# Generated by Django 5.1.1 on 2024-10-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_sharedchart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedchart',
            unique_together={('file_id', 'chart_type')},
        ),
    ]
