# Generated by Django 5.1.1 on 2024-10-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_sharedchart_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedchart',
            unique_together=set(),
        ),
    ]
