# Generated by Django 5.1.1 on 2024-10-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_sharedchart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedchart',
            name='unique_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
